sudo: required

language: generic

services:
  - docker

before_install:
  - echo "start Creating an image with dockerfile"
  - docker build -t ksaid0203/docker-react-app -f Dockerfile.dev .

script: 
  - docker run -e CI=true ksaid0203/docker-react-app npm run test -- --coverage

after_success: 
  - echo "Test Success"